### ISSUE TITLE
Provider-specific configuration from other eDNS instances breaks this webhook

### ISSUE THREAD

**Issue by mircea-pavel-anton** [mirceanton/external-dns-provider-mikrotik#140]
If you have multiple external DNS instances, for example this one and cloudflare and you add annotations for both on the same ingress, such as:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  namespace: test
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.example.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.example.com
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  number: 80
            path: /
            pathType: Prefix

```

Then the mikrotik webhook will complain that `cloudflare-proxied` is an invalid provider-specific configuration.

This is likely a bug in the upstream external-dns since we should only be getting our webhook annotations and no vendor-specific ones.
