### ISSUE TITLE
Mirkotik configuration exmaple

### ISSUE THREAD

**Issue by mrkhachaturov** [mirceanton/external-dns-provider-mikrotik#211]
Hello, thank you for this project. 
Can you please provide some configuration example for Router OS?

**Comment by mircea-pavel-anton** [comment]
Hello, @mrkhachaturov !

> Can you please provide some configuration example for Router OS?

Can you expand a bit, please? What kind of configuration you mean?

**Comment by mrkhachaturov** [comment]
I have external-dns deployed for cloudflare. 
Trying to deploy second for use with Router OS 
```yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    # logLevel: debug
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
          tag: v1.4.4@sha256:d51055ef8f9311373e0b16057b34dbbb393a8f29248431f4ddd9279a417f602d
          pullPolicy: IfNotPresent
        env:
          - name: LOG_FORMAT
            value: json
          - name: LOG_LEVEL
            value: debug

          - name: MIKROTIK_DEFAULT_TTL
            value: "1800"
          - name: MIKROTIK_DEFAULT_COMMENT
            value: Managed by ExternalDNS

          - name: MIKROTIK_BASEURL
            valueFrom:
              secretKeyRef:
                name: &secret internal-external-dns-secret
                key: MIKROTIK_BASEURL
          - name: MIKROTIK_USERNAME
            valueFrom:
              secretKeyRef:
                name: *secret
                key: MIKROTIK_USERNAME
          - name: MIKROTIK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: MIKROTIK_PASSWORD
          - name: MIKROTIK_SKIP_TLS_VERIFY
            valueFrom:
              secretKeyRef:
                name: *secret
                key: MIKROTIK_SKIP_TLS_VERIFY

        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --ignore-ingress-tls-spec
      - --managed-record-types=A
    triggerLoopOnEvent: true
    policy: sync
    sources: ["ingress", "service"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret

```
MIKROTIK_SKIP_TLS_VERIFY is true.
I have defined mikrotik_base_url `http://192.168.10.1:8728` where `192.168.10.1` is Router IP and default gateway in my kernetes network. 
`8728` is the port of `api` service. 
```shell
Columns: NAME, PORT, CERTIFICATE, VRF, MAX-SESSIONS
#   NAME     PORT  CERTIFICATE  VRF   MAX-SESSIONS
0   telnet     23               main            20
1   ftp        21               main            20
2 X www        80               main            20
3   ssh        22               main            20
4 X www-ssl   443  none         main            20
5   api      8728               main            20
6   winbox   8291               main            20
7   api-ssl  8729  none         main            20
```

Here are logs from pods `webhook` container: 
```log
{"level":"info","msg":"starting external-dns-provider-mikrotik version: 1.4.4 (d95da04)","time":"2025-03-09T23:42:37Z"}
{"level":"info","msg":"creating mikrotik provider with no kind of domain filters","time":"2025-03-09T23:42:37Z"}
{"level":"info","msg":"creating a new Mikrotik API Client","time":"2025-03-09T23:42:37Z"}
{"level":"debug","msg":"fetching system information.","time":"2025-03-09T23:42:37Z"}
{"level":"debug","msg":"sending GET request to: http://192.168.10.1:8728/rest/system/resource","time":"2025-03-09T23:42:37Z"}
```

logs from `external-dns` container:

```log
time="2025-03-09T23:45:24Z" level=info msg="config: {APIServerURL: KubeConfig: RequestTimeout:30s DefaultTargets:[] GlooNamespaces:[gloo-system] SkipperRouteGroupVersion:zalando.org/v1 Sources:[ingress service] Namespace: AnnotationFilter: LabelFilter: IngressClassNames:[] FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false IgnoreIngressTLSSpec:true IgnoreIngressRulesSpec:false GatewayNamespace: GatewayLabelFilter: Compatibility: PublishInternal:false PublishHostIP:false AlwaysPublishNotReadyAddresses:false ConnectorSourceServer:localhost:8080 Provider:webhook ProviderCacheTime:0s GoogleProject: GoogleBatchChangeSize:1000 GoogleBatchChangeInterval:1s GoogleZoneVisibility: DomainFilter:[astrateam.net] ExcludeDomains:[] RegexDomainFilter: RegexDomainExclusion: ZoneNameFilter:[] ZoneIDFilter:[] TargetNetFilter:[] ExcludeTargetNets:[] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType: AWSZoneTagFilter:[] AWSAssumeRole: AWSProfiles:[] AWSAssumeRoleExternalID: AWSBatchChangeSize:1000 AWSBatchChangeSizeBytes:32000 AWSBatchChangeSizeValues:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AWSPreferCNAME:false AWSZoneCacheDuration:0s AWSSDServiceCleanup:false AWSSDCreateTag:map[] AWSZoneMatchParent:false AWSDynamoDBRegion: AWSDynamoDBTable:external-dns AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup: AzureSubscriptionID: AzureUserAssignedIdentityClientID: AzureActiveDirectoryAuthorityHost: AzureZonesCacheDuration:0s CloudflareProxied:false CloudflareDNSRecordsPerPage:100 CloudflareRegionKey: CoreDNSPrefix:/skydns/ AkamaiServiceConsumerDomain: AkamaiClientToken: AkamaiClientSecret: AkamaiAccessToken: AkamaiEdgercPath: AkamaiEdgercSection: OCIConfigFile:/etc/kubernetes/oci.yaml OCICompartmentOCID: OCIAuthInstancePrincipal:false OCIZoneScope:GLOBAL OCIZoneCacheDuration:0s InMemoryZones:[] OVHEndpoint:ovh-eu OVHApiRateLimit:20 PDNSServer:http://localhost:8081 PDNSServerID:localhost PDNSAPIKey: PDNSSkipTLSVerify:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:main TXTPrefix:k8s.main. TXTSuffix: TXTEncryptEnabled:false TXTEncryptAESKey: Interval:1m0s MinEventSyncInterval:5s Once:false DryRun:false UpdateEvents:true LogFormat:text MetricsAddress::7979 LogLevel:info TXTCacheInterval:0s TXTWildcardReplacement: ExoscaleEndpoint: ExoscaleAPIKey: ExoscaleAPISecret: ExoscaleAPIEnvironment:api ExoscaleAPIZone:ch-gva-2 CRDSourceAPIVersion:externaldns.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] CFAPIEndpoint: CFUsername: CFPassword: ResolveServiceLoadBalancerHostname:false RFC2136Host: RFC2136Port:0 RFC2136Zone:[] RFC2136Insecure:false RFC2136GSSTSIG:false RFC2136CreatePTR:false RFC2136KerberosRealm: RFC2136KerberosUsername: RFC2136KerberosPassword: RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false RFC2136MinTTL:0s RFC2136BatchChangeSize:50 RFC2136UseTLS:false RFC2136SkipTLSVerify:false NS1Endpoint: NS1IgnoreSSL:false NS1MinTTLSeconds:0 TransIPAccountName: TransIPPrivateKeyFile: DigitalOceanAPIPageSize:50 ManagedDNSRecordTypes:[A] ExcludeDNSRecordTypes:[] GoDaddyAPIKey: GoDaddySecretKey: GoDaddyTTL:0 GoDaddyOTE:false OCPRouterName: IBMCloudProxied:false IBMCloudConfigFile:/etc/kubernetes/ibmcloud.json TencentCloudConfigFile:/etc/kubernetes/tencent-cloud.json TencentCloudZoneType: PiholeServer: PiholePassword: PiholeTLSInsecureSkipVerify:false PluralCluster: PluralProvider: WebhookProviderURL:http://localhost:8888 WebhookProviderReadTimeout:5s WebhookProviderWriteTimeout:10s WebhookServer:false TraefikDisableLegacy:false TraefikDisableNew:false NAT64Networks:[]}"
time="2025-03-09T23:45:24Z" level=info msg="Instantiating new Kubernetes client"
time="2025-03-09T23:45:24Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2025-03-09T23:45:24Z" level=info msg="Created Kubernetes client https://172.22.0.1:443"
time="2025-03-09T23:45:30Z" level=fatal msg="failed to connect to webhook: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
```
