### ISSUE TITLE
Bug: Record "disabled" status is ignored

### ISSUE THREAD

**Issue by mircea-pavel-anton** [mirceanton/external-dns-provider-mikrotik#78]
Currently, we can configure the `disabled` status (`true`/`false`) of a DNS record in the RouterOS API via the `providerSpecific` section of a DNSEndpoint object, like so:

```yaml
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: a-record
spec:
  endpoints:
    - dnsName: example.com
      recordTTL: 180
      recordType: A
      targets:
        - 1.2.3.4
      providerSpecific:
        - name: disabled
          value: true
        - name: comment
          value: "This is a comment"
        - name: address-list
          value: "1.2.3.1"
        - name: match-subdomain
          value: "true"
```

However, the problem here is that such a field is not actually a hard requirement, i.e. we can create a "basic" DNSEndpoint like so:

```yaml
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: a-record
spec:
  endpoints:
    - dnsName: example.com
      recordTTL: 3605
      recordType: A
      targets:
        - 192.192.192.192

```

This becomes a problem because by default, creating this DNS Record in the RouterOS API will set `disabled: false`, thus creating a discrepancy between the expected state (no disabled) and current state (disabled: false). This will cause the record to be deleted and re-created on every reconciliation loop.

For now, I ended up removing the `disabled` field entirely, so it is completely ignored.

If there is any traction for a configurable `disabled` field, we can investigate a solution to work around this issue.
